import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
import { AppProvider } from "@/context/AppContext";

import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="coffee">
      <body className={inter.className}>
        <AppProvider>
          <Navbar />
          <main className="justify-center items-center mx-auto bg-base-100 w-full max-w-screen">
            <div className="w-full max-w-screen overflow-hidden">
              {children}
            </div>
          </main>
          <ToastContainer />
        </AppProvider>
      </body>
    </html>
  );
}
